# Generated by Django 3.1.3 on 2020-11-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200807_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
